[package]
name = "secrets_agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai_api_rust = "0.1.8"
actix-web = "4"
actix-multipart = "0.6.1"
futures-util = "0.3.30"